version: "3.7"

services:
  runner:
    build:
      context: .
      dockerfile: runner/Dockerfile
    network_mode: host
    user: "1000:1000"
    volumes:
      - ${LIGHT_STORES_DIR:-/mnt/md0/light-stores/}:${LIGHT_STORES_DIR:-/mnt/md0/light-stores/}
    restart: always
  rtsp:
    build: rtsp
    restart: always
    network_mode: host
    ports:
      - 8554:8554
      - 8888:8888
      - 8889:8889
    volumes:
      - ./rtsp/rtsp-simple-server.yml:/rtsp-simple-server.yml
      - ./rtsp/scripts:/scripts
      - ${LIGHT_STORES_DIR:-/mnt/md0/light-stores/}/kv:/config
    devices:
      - ${TOP_CAM:-/dev/video2}:/dev/top-cam
      - ${FRONT_CAM:-/dev/video0}:/dev/front-cam
  pygateway:
    build: pygateway
    devices:
      - /dev/ttyACM0
    tty: true
    restart: always
    network_mode: host
    environment:
      BROKER_HOST: ${BROKER_HOST:-localhost}
      DEBUG_PYGATEWAY: ${DEBUG_PYGATEWAY:-false}
  goo:
    build:
      context: .
      dockerfile: goo/Dockerfile
    command: -basePath ${LIGHT_STORES_DIR:-/mnt/md0/light-stores/}
    restart: always
    network_mode: host
    volumes:
      - ${LIGHT_STORES_DIR:-/mnt/md0/light-stores/}:${LIGHT_STORES_DIR:-/mnt/md0/light-stores/}
      - /dev:/dev
    user: "1000:1000"
    enviornment:
      ENABLE_EBS: ${ENABLE_EBS:-false}
  dslrcapture:
    build:
      context: .
      dockerfile: dslrcapture/Dockerfile
    command: -basePath ${LIGHT_STORES_DIR:-/mnt/md0/light-stores/}
    restart: always
    privileged: true
    network_mode: host
    environment:
      MOCK_DSLR: ${MOCK_DSLR:-false}
    volumes:
      - ${LIGHT_STORES_DIR:-/mnt/md0/light-stores/}:${LIGHT_STORES_DIR:-/mnt/md0/light-stores/}
      - /dev:/dev
  interface:
    build:
      context: ./interface
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:80"
